/* eslint-disable import/no-anonymous-default-export */
export default {
  login: "aditya-tri",
  id: 83681201,
  node_id: "MDQ6VXNlcjgzNjgxMjAx",
  avatar_url: "https://avatars.githubusercontent.com/u/83681201?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/aditya-tri",
  html_url: "https://github.com/aditya-tri",
  followers_url: "https://api.github.com/users/aditya-tri/followers",
  following_url:
    "https://api.github.com/users/aditya-tri/following{/other_user}",
  gists_url: "https://api.github.com/users/aditya-tri/gists{/gist_id}",
  starred_url: "https://api.github.com/users/aditya-tri/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/aditya-tri/subscriptions",
  organizations_url: "https://api.github.com/users/aditya-tri/orgs",
  repos_url: "https://api.github.com/users/aditya-tri/repos",
  events_url: "https://api.github.com/users/aditya-tri/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/aditya-tri/received_events",
  type: "User",
  site_admin: false,
  name: "Aditya Trisakti",
  company: null,
  blog: "",
  location: "Medan, Indonesia",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: "adityaa_tri",
  public_repos: 6,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2021-05-05T01:06:44Z",
  updated_at: "2022-01-30T08:11:43Z",
};
